/* 框架安装存在故障，没有切换到指定数据源上，临时在脚本中指定库名，但ORM脚本应与业务无关。 */
USE UEP4X;
/* 多表定义表 */
IF  EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='MULTI_TABLE_DEFINITION_TABLE')
  DROP TABLE MULTI_TABLE_DEFINITION_TABLE
GO
CREATE TABLE MULTI_TABLE_DEFINITION_TABLE 
(
   ID                   VARCHAR(100)                   not null,
   DESCRIPTION          NVARCHAR(500)                   null,
   COMBINATIVE_TABLE    VARCHAR(500)                   null,
   PROJECT_NAME         VARCHAR(100)                   null,
   SCENE                TINYINT                        null,
   CONSTRAINT PK_MULTI_TABLE_DEFINITION_TABL PRIMARY KEY (ID)
);
/* 多表定义字段表 */
IF  EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='MULTI_TABLE_METADATA_TABLE')
  DROP TABLE MULTI_TABLE_METADATA_TABLE
GO
CREATE TABLE MULTI_TABLE_METADATA_TABLE 
(
   ID                   VARCHAR(32)                    not null,
   RESOURCE_ID          VARCHAR(100)                   null,
   TABLE_NAME           VARCHAR(100)                   null,
   TABLE_COLUMN_NAME    VARCHAR(100)                   null,
   RESOURCE_COLUMN_NAME VARCHAR(100)                   null,
   DATABASE_NAME		VARCHAR(100) 				   null,
   CONSTRAINT PK_MULTI_TABLE_METADATA_TABLE PRIMARY KEY (ID)
);
/* 单表定义表 TABLE_TYPE（“0”为单表，“1”为视图） */
IF  EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='SINGLE_TABLE_DEFINITION_TABLE')
  DROP TABLE SINGLE_TABLE_DEFINITION_TABLE
GO
CREATE TABLE SINGLE_TABLE_DEFINITION_TABLE 
(
   TABLE_NAME           VARCHAR(64)                    not null,
   DESCRIPTION          NVARCHAR(200)                  null,
   TABLE_TYPE           TINYINT                        null,
   CONSTRAINT PK_SINGLE_TABLE_DEFINITION_TABLE PRIMARY KEY (TABLE_NAME)
);
/* 单表和多表定义视图，TABLE_TYPE（“0”为单表，“1”为视图，“2”为多表） */
IF  EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='TABLE_DEFINITION_VIEW')
  DROP VIEW TABLE_DEFINITION_VIEW
GO
CREATE VIEW TABLE_DEFINITION_VIEW AS SELECT
	stdt.TABLE_NAME AS TABLE_NAME,
	stdt.DESCRIPTION AS DESCRIPTION,
	stdt.TABLE_TYPE AS TABLE_TYPE
FROM
	SINGLE_TABLE_DEFINITION_TABLE stdt
UNION
	SELECT
		mtdt.ID AS TABLE_NAME,
		mtdt.DESCRIPTION AS DESCRIPTION,
		'2' AS TABLE_TYPE
	FROM
		MULTI_TABLE_DEFINITION_TABLE mtdt
	WHERE mtdt.SCENE = 1;