DROP SCHEMA IF EXISTS `GLOBAL`;
CREATE SCHEMA `GLOBAL` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP SCHEMA IF EXISTS `TENANT`;
CREATE SCHEMA `TENANT` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP SCHEMA IF EXISTS `COS_BPE`;
CREATE SCHEMA `COS_BPE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CALL MAO.cleanSchema('TENANT_');