DROP SCHEMA IF EXISTS `D_GLOBAL`;
CREATE SCHEMA `D_GLOBAL` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP SCHEMA IF EXISTS `D_TENANT`;
CREATE SCHEMA `D_TENANT` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

DROP SCHEMA IF EXISTS `D_COS_BPE`;
CREATE SCHEMA `D_COS_BPE` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

CALL MAO.cleanSchema('D_TENANT_');