package com.zte.mao.workbench.def;

public interface TDataModelItem {
    int ENUM_TYPE_STRING = 1;
    int ENUM_TYPE_LONG_STRING = 2;
    int ENUM_TYPE_BOOLEAN = 3;
    int ENUM_TYPE_INTERGE = 4;
    int ENUM_TYPE_FLOAT = 5;
    int ENUM_TYPE_DATE = 6;
    int ENUM_TYPE_BIGINT = 7;
    int ENUM_TYPE_DOUBLE = 8;
    
    int ENUM_LAYOUT_HALF_LINE_CAN_HAVE_OTHER = 0;
    int ENUM_LAYOUT_EXCLUSIVE_LINE = 1;
    int ENUM_LAYOUT_EXCLUSIVE_HALF_LINE = 2;
    
    int ENUM_COMPONENT_TYPE_LABLE = 1;
    int ENUM_COMPONENT_TYPE_INPUT_TEXT = 2;
    int ENUM_COMPONENT_TYPE_TEXTAREA = 3;
    int ENUM_COMPONENT_TYPE_SELECT_DYNAMIC = 4;
    int ENUM_COMPONENT_TYPE_INPUT_RADIO = 5;
    int ENUM_COMPONENT_TYPE_CHECKBOX = 6;
    int ENUM_COMPONENT_TYPE_INPUT_DATETIME = 7;
    int ENUM_COMPONENT_TYPE_INPUT_FILEINPUT = 8;

    String SCHEMA = STenant.NAME;
    String NAME = "DATA_MODEL_ITEM_TABLE";

    String COL_NAME_ID = "ID";
    String COL_NAME_NAME = "NAME";
    String COL_NAME_MODEL_ID = "MODEL_ID";
    String COL_NAME_TYPE = "TYPE";
    String COL_NAME_IS_NULL = "IS_NULL";
    String COL_NAME_COLUMN_KEY = "COLUMN_KEY";
    String COL_NAME_LENGTH = "LENGTH";
    String COL_NAME_DECIMAL = "DECIMAL";
    String COL_NAME_DEFAULT = "DEFAULT";
    String COL_NAME_INDEX = "INDEX";
    String COL_NAME_COMPONENT_TYPE = "COMPONENT_TYPE";
    String COL_NAME_UI_VISIBLE = "UI_VISIBLE";
    String COL_NAME_LAYOUT = "LAYOUT";
    String COL_NAME_DATA_BLOCK = "DATA_BLOCK";
}
