package com.zte.mao.bpm.def;

public interface VDataModelMethodParameter {
    int ENUM_PARAMETER_TYPE_OUPUT = 1;
    int ENUM_PARAMETER_TYPE_INPUT = 2;
    int ENUM_PARAMETER_TYPE_INOUTPUT = 3;

    int ENUM_MAP_TYPE_BIND = 1;
    int ENUM_MAP_TYPE_CONST = 2;

    String SCHEMA = STenant.NAME;
    String NAME = "DATA_MODEL_METHOD_PARAMETER_VIEW";
    String COL_NAME_MODEL_ID = "MODEL_ID";
    String COL_NAME_METHOD_ID = "METHOD_ID";
    String COL_NAME_BIZ_VARIABLE_ID = "BIZ_VARIABLE_ID";
    String COL_NAME_PARAMETER_TYPE = "PARAMETER_TYPE";
    String COL_NAME_MAP_TYPE = "MAP_TYPE";
    String COL_NAME_MAP_VALUE = "MAP_VALUE";
    String COL_NAME_ITEM_NAME = "ITEM_NAME";
    String COL_NAME_ITEM_TYPE = "ITEM_TYPE";
    String COL_NAME_ITEM_IS_NULL = "ITEM_IS_NULL";
    String COL_NAME_ITEM_COLUMN_KEY = "ITEM_COLUMN_KEY";
    String COL_NAME_ITEM_LENGTH = "ITEM_LENGTH";
    String COL_NAME_ITEM_DECIMAL = "ITEM_DECIMAL";
    String COL_NAME_ITEM_DEFAULT = "ITEM_DEFAULT";

    String[] COLUMNS = new String[] {
        COL_NAME_MODEL_ID,
        COL_NAME_METHOD_ID,
        COL_NAME_BIZ_VARIABLE_ID,
        COL_NAME_PARAMETER_TYPE,
        COL_NAME_MAP_TYPE,
        COL_NAME_MAP_VALUE,
        COL_NAME_ITEM_NAME,
        COL_NAME_ITEM_TYPE,
        COL_NAME_ITEM_IS_NULL,
        COL_NAME_ITEM_COLUMN_KEY,
        COL_NAME_ITEM_LENGTH,
        COL_NAME_ITEM_DECIMAL,
        COL_NAME_ITEM_DEFAULT
        };
}
